apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
spec:
  containers:
  - name: tensorflow-cpu-{{.Name}}
    image: {{.Imagename}}
    command:
    - "/bin/bash"
    - "-c"
    - "{{.Command}}" 
    resources:
      requests:
        cpu: 20
        memory: 1G
      limits:
        cpu: 20
        memory: 1G
    volumeMounts:
    - name: nvidia-driver-384-111
      mountPath: /usr/local/nvidia
      readOnly: true
    - name: libcuda-so
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
    - name: libcuda-so-1
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    - name: libcuda-so-384-111
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.384.111
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: nvidia-driver-384-111
    hostPath:
      path: /usr/lib/nvidia-384
  - name: libcuda-so
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so
  - name: libcuda-so-1
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  - name: libcuda-so-384-111
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.384.111
